#!/bin/bash

function usage () {
   echo "$0 [-i jar2install-version.jar] [-s (search for groupid|artifactId)]"
}

function set_import_values() {

    JARFILE=$1
    GROUPID=$2
    ARTIFACTID=$3
    VERSION=$4

    while true; do 
        echo "Verify the following values are correct:"
        echo " 1) Group ID: $GROUPID"
        echo " 2) Artifact: $ARTIFACTID"
        echo " 3) Version:  $VERSION"
        echo " 4) Packaging: $PACKAGING"

        echo "To make changes, enter the line number and the new value(i.e. '3 1.0'): "
        read INPUT
        selection=${INPUT[@]:0:1}
        value=${INPUT[@]:1}
        case "$selection" in
            1) GROUPID=$value;;
            2) ARTIFACTID=$value;;
            3) VERSION=$value;;
            4) PACKAGING=$value;;
            *) break;;
        esac
    done

}

PACKAGING="jar"
LOCALREPO="~/.m2/repository"
JARFILE=""
GROUPID=""
ARTIFACTID=""
VERSION=""

function install() {
    jarfile=$1;
    version=$(expr match "$jarfile" '.*-\(.*\)\.jar')
    fullclass=$(jar -tf "$jarfile" | tail -n 1)
    groupId=$(expr match "$fullclass" '\(\w*\/\w*\)\/.*')
    groupId=${groupId/\//.}
    artifactId=$(expr match "$fullclass" '\w*\/\w*\/\(\w*\)\/.*')
    
    set_import_values $jarfile $groupId $artifactId $version 
    arguments="-Dfile=$JARFILE -DgroupId=$GROUPID -DartifactId=$ARTIFACTID -Dversion=$VERSION -Dpackaging=$PACKAGING"
    if [ 'java-source' = "$PACKAGING" ]; then
        arguments="$arguments -DgeneratePom=false"
    fi

    echo "Installing $jarfile with the arguments $arguments"

    mvn install:install-file $arguments
}

function search() {
    echo "not yet implemented"
}


while getopts i:s:h flag
do
    case "$flag" in
        i) install $OPTARG;;
        s) search $OPTARG;;
        h) usage;exit 0;;
        *) usage;exit 1;;
    esac
done


